### ISSUE TITLE
[feature] Version tagged images in hub.docker

### ISSUE THREAD

**Issue by alexdyas** [Praqma/Network-MultiTool#11]
Great tool. Suggestion - version tagged images in hub.docker instead of just 'latest'. Makes it easier to get K8s to recognize and fetch a new version. Also always safer to pin to a version and consciously update in a controlled way.

Cheers

**Comment by KamranAzeem** [comment]
Thanks for appreciation! I will look into your suggestion.

:)

**Comment by KamranAzeem** [comment]
Version is now a tag, and is also an automated build. Thanks for the suggestion.

https://hub.docker.com/repository/docker/praqma/network-multitool
