### ISSUE TITLE
iptables-save doesn't work

### ISSUE THREAD

**Issue by Axizdkr** [Praqma/Network-MultiTool#13]
when i try to execute `iptables-save`
got an error `iptables-save v1.8.4 (legacy): Cannot initialize: Permission denied (you must be root)`
but i'm root (#)
![image](https://user-images.githubusercontent.com/45120889/94105144-4f995680-fe41-11ea-9f9c-c748ab67190a.png)

**Comment by KamranAzeem** [comment]
docker run --cap-add=NET_ADMIN --cap-add=NET_RAW \
  --name multitool  \
  -it praqma/network-multitool /bin/bash

**Comment by Axizdkr** [comment]
thx
