### ISSUE TITLE
请问下这个工具集成的nginx现在没有stream模块，怎么安装呢？

### ISSUE THREAD

**Issue by luke-zhang580** [Praqma/Network-MultiTool#14]

**Comment by hoeghh** [comment]
Freely translated with google translate
"Is there no nginx integrated with this tool?
Module, how to install it"

**Comment by hoeghh** [comment]
Yes, as stated throughout the README.md file, the docker image do have nginx installed. 
It listens on port `80` and `443`. 

Its installed here :
https://github.com/Praqma/Network-MultiTool/blob/master/Dockerfile#L12

And i copies a html file into the container here :
https://github.com/Praqma/Network-MultiTool/blob/master/Dockerfile#L23

And copy a nginx conf file into the container here :
https://github.com/Praqma/Network-MultiTool/blob/master/Dockerfile#L26

Let us know if you have questions or problems getting it up and running.

**Comment by luke-zhang580** [comment]
Thank you, the stream module is not installed in nginx in the toolkit. I need to use it to forward intranet MySQL connections. How should I configure it?

**Comment by hoeghh** [comment]
@KamranAzeem Do you know about this?

@luke-zhang580 The container is mainly meant to be use for testing things, not a container to use for real things. Is the stream module used for testing purposes?

**Comment by luke-zhang580** [comment]
Yes, I already know that it is mainly used for testing, now that it has nginx, whether it can support the stream module of nginx, I think it will be better.

**Comment by KamranAzeem** [comment]
Thank you for taking interest in, and using Network-Multitool. 

Your question is already answered under the FAQs in the main page. It is copied below for your reference. I hope it helps.

> I can't find a tool I need for my use-case?
> We have tried to put in all the most commonly used tools, while keeping it small and practical. We can't have all the tools under the sun in it, otherwise it will end up as something like this.
> 
> However, if you have a special need, for a special tool, for your special use-case, then I would recommend to simply build your own docker image using this one as base image, and expanding it with the tools you need.
>
