### ISSUE TITLE
Configuration of Nginx ports no longer works

### ISSUE THREAD

**Issue by michaelin** [Praqma/Network-MultiTool#15]
It is no longer possible to change HTTP and HTTPS port at runtime. Setting HTTP_PORT and HTTPS_PORT has no effect, and nginx will always run on port 80/443.

The issue has been introduced in [b301503](https://github.com/Praqma/Network-MultiTool/commit/b301503492c8bc7356453f8e9bada6dfa07ed916) where `/etc/nginx/conf.d/default.conf` was merged into `/etc/nginx/nginx.conf`. The problem is that `docker-entrypoint.sh` still updates the old `default.conf`, which is no longer read.

The config merge should either be rolled back, or the `docker-entrypoint.sh` script should be changed to update `nginx.conf`.

**Comment by KamranAzeem** [comment]
Thank you for pointing it out! Unfortunately I did not find time to attend this earlier. I have now fixed this problem.
