### ISSUE TITLE
how about the dhcpclient tool 👀

### ISSUE THREAD

**Issue by TheMasterOfMagic** [Praqma/Network-MultiTool#19]
I'm not sure if make DHCP request as client is a missing common use-case or just my special one.   

If so would you mind adding it under the extra tag？

**Comment by KamranAzeem** [comment]
I don't see it as a common use-case, and not even fitting under "extra". 

For you use-case, feel free to build your own image based on this one, with dhcpclient included.

**Comment by TheMasterOfMagic** [comment]
sure
