### ISSUE TITLE
ping: socket: Operation not permitted

### ISSUE THREAD

**Issue by dalekseevs** [Praqma/Network-MultiTool#22]
When trying to ping IPs or adresses an error is returned
`ping: socket: Operation not permitted`

I am deploying to a GKE autopilot cluster with `kubectl run multitool --image=praqma/network-multitool:extra`

Is this normal behaviour or is there a problem wit the image?

**Comment by KamranAzeem** [comment]
Please provide more information on what you are trying to do, such as the exact command you are trying to execute, with complete output. 

Here is my example, where I can see that it works on my cluster:

```
[kamran@kworkhorse ~]$ kubectl --namespace=test run multitool --image=praqma/network-multitool:extra
pod/multitool created


[kamran@kworkhorse ~]$ kubectl --namespace=test get pods
NAME                                        READY   STATUS             RESTARTS   AGE
multitool                                   1/1     Running            0          14s
```

Ping google DNS server:
```
[kamran@kworkhorse ~]$ kubectl --namespace=test exec -it multitool /bin/sh

/ # ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=121 time=3.55 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=121 time=2.20 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 2.195/2.870/3.545/0.675 ms
/ # exit
[kamran@kworkhorse ~]$ 
```

**Comment by KamranAzeem** [comment]
PS. My K8s cluster is a GKE cluster, but not an "autopilot" cluster.

**Comment by dalekseevs** [comment]
That's exactly what I am doing:

```
kubectl exec -it multitool -- /bin/bash
bash-5.1# ping 10.8.4.6
ping: socket: Operation not permitted
```

**Comment by KamranAzeem** [comment]
May be some permissions/privileges issue on the namespace you are running the container in. As you can see from my reply above, I don't see this problem, so it looks like this is not a problem with the image.

**Comment by dalekseevs** [comment]
I agree I think it a problem on my side.
